### ISSUE TITLE
tabhost with multitab crash..

### ISSUE THREAD

**Issue by avary** [JouriM66/DPF.Android.Native.Components#1]
Hi
im trying to use your delphi android native components with RAD XE10 seattle.
whenever i use tabhost i crash with following error
I/info    ( 4816): Project1TDPFANDBaseControl.Resize: TDPFJTabHost Name: DPFJTabHost1
D/NativeLayout( 4816): setPosition 0 0 mLayout=com.embarcadero.firemonkey.nativelayout.NativeLayout$LinearLayout2{430cc338 V....... ......I. 0,0-0,0}
I/info    ( 4816): Project1TDPFANDBaseControl.AddSubView(Handle): DPFJTabHost1
I/info    ( 4816): Project1TDPFANDBaseControl.Loaded: TDPFJTabHost Name: DPFJTabHost1 Unit: DPF.Android.JTabHost
I/info    ( 4816): Project1TDPFANDBaseControl.Resize: TDPFAndroidTabBarItem Name: DPFAndroidTabBarItem1
I/info    ( 4816): Project1TDPFANDBaseControl.Resize: TDPFJTabHost Name: DPFJTabHost1
I/info    ( 4816): Project1TDPFANDBaseControl.Resize: TDPFJTabHost Name: DPFJTabHost1
I/info    ( 4816): Project1TDPFANDBaseControl.Resize: TDPFAndroidTabBarItem Name: DPFAndroidTabBarItem1
I/info    ( 4816): Project1TDPFANDBaseControl.Resize: TDPFJTabHost Name: DPFJTabHost1
D/OpenGLRenderer( 4816): Enabling debug mode 0
D/NativeLayout( 4816): setPosition 0 0 mLayout=com.embarcadero.firemonkey.nativelayout.NativeLayout$LinearLayout2{430cc338 V....... ......ID 0,0-1760,1320}
D/NativeLayout( 4816): setPosition 0 0 mLayout=com.embarcadero.firemonkey.nativelayout.NativeLayout$LinearLayout2{430cc338 V....... ......ID 0,0-1760,1320}
D/NativeLayout( 4816): setPosition 0 0 mLayout=com.embarcadero.firemonkey.nativelayout.NativeLayout$LinearLayout2{430cc338 V....... ......ID 0,0-1760,1320}
D/AndroidRuntime( 4816): Shutting down VM
W/dalvikvm( 4816): threadid=1: thread exiting with uncaught exception (group=0x41772d58)
E/AndroidRuntime( 4816): FATAL EXCEPTION: main
E/AndroidRuntime( 4816): Process: com.embarcadero.Project1, PID: 4816
E/AndroidRuntime( 4816): java.lang.ClassCastException: android.widget.RelativeLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams
E/AndroidRuntime( 4816):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:311)
E/AndroidRuntime( 4816):        at android.view.View.measure(View.java:16529)
E/AndroidRuntime( 4816):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime( 4816):        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
E/AndroidRuntime( 4816):        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
E/AndroidRuntime( 4816):        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
E/AndroidRuntime( 4816):        at android.view.View.measure(View.java:16529)
E/AndroidRuntime( 4816):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime( 4816):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime( 4816):        at android.view.View.measure(View.java:16529)
E/AndroidRuntime( 4816):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime( 4816):        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
E/AndroidRuntime( 4816):        at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1052)
E/AndroidRuntime( 4816):        at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
E/AndroidRuntime( 4816):        at android.view.View.measure(View.java:16529)

I/octvm_klo( 1973): [am_crash][1460909925]:[4816,0,com.embarcadero.Project1,8961606,java.lang.ClassCastException,android.widget.RelativeLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams,FrameLayout.java,311]

i think it happens on Resize but cannot fix it, whould you please take a look ? or tell me where should i look in the code to fix it ?

**Comment by JouriM66** [comment]
It seems components incorrectly use layout params
But I cant fix it, sorry
Im not a author, I just correct them to compile on modern embarcadero products.
The embarcadero and components both are very buggy and I give up to use them
